### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by Turiinjargal** [biligunb/qplugin#25]
After checkout under 10₮
![image](https://user-images.githubusercontent.com/25520812/166404298-0fb9eeab-e1e3-4aba-8719-c0e12c3bbb31.png)
After checkout greater 10₮
![Screen Shot 2022-05-03 at 12 14 24](https://user-images.githubusercontent.com/25520812/166404373-2ea1c8f9-2985-4322-896b-7c0fd8e88153.png)

**Comment by biligunb** [comment]
@Turiinjargal 
1. QPay-н төлбөрийн хэмжээгээ documentation-с нь сайн харна уу
2. Ямар hosting дээр байдаг вэ? (shared?)
    - энэ 502 заасан нь browser-с хандаж GET request шидээд байна уу?
    - log байгаа юу wp-debug.log

**Comment by Turiinjargal** [comment]
@biligunb 
1. Төлбөрийн хэмжээ 10 төгрөгөөс дээш хийж байгаа. Эхлээд тест эрхээр үзэж байна.
2. VPS дээр байдаг. Ubuntu 20.04, php7.4, mysql 8.
3. Яг гол асуудал нь товч дарахад секүнд явж эхлээд QR зураг нь харагдахгүй байгаа. Би webhook -дээ байнуу гэж бодоод байна
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/25520812/168489536-096b9a9a-c5fa-4fa3-a8e7-c07a85917e26.png">

**Comment by Turiinjargal** [comment]
@biligunb www.erdmeat.mn гэж ороод үзээрэй

**Comment by Turiinjargal** [comment]
Ядаж байхад qpay.mn веб нь болохгүй байх юм
эндээс харахад access_token авч чадахгүй байх шиг байна. 
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/25520812/168489618-eb83db12-74bf-43b4-b767-8388b434affc.png">

**Comment by Turiinjargal** [comment]
@biligunb woocommerce setting ороод qpay invoice, user,pass тохируулчихаад эхний удаа төлбөр төлөх дарахаар 502 болоод байгаа. 
![Uploading image.png…]()

**Comment by Turiinjargal** [comment]
@biligunb debug.log дээр ийм байна. Би серверийн цаг utc8, wp-config utc8 гэж тааруулсын уул нь тэгсэн debug.log 8 цаг зөрүүтэй харагдаад болдоггүй
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/25520812/168490112-3be9f73b-3c3c-41f1-a8fa-4de3c241b4dc.png">

**Comment by Turiinjargal** [comment]
https:\/\/erdmeat.mn\/wc-api\/qplugin?id=11985 дээр -1 гарч ирж байна
<img width="479" alt="image" src="https://user-images.githubusercontent.com/25520812/168490545-0dc44b32-dffa-45e8-a3d4-f0f68c0ecf97.png">

**Comment by Turiinjargal** [comment]
auth хийж чадахгүй байгаа юм байна. invoice params 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/25520812/168490589-b962b9af-8097-4034-ac72-e7b9c7cea2c3.png">

**Comment by Turiinjargal** [comment]
invoice user pass аа буруу тохируулж байсан байна сорри :D
<img width="814" alt="image" src="https://user-images.githubusercontent.com/25520812/168491206-ba2e68b3-425c-4e61-afe7-65b6756e76aa.png">

**Comment by Turiinjargal** [comment]
Баярлалаа! Гоё юм хийсэн байна @biligunb
