### ISSUE TITLE
Invoice үүсэх үед $invoice_due_date буруу бодож байна.

### ISSUE THREAD

**Issue by btulga** [biligunb/qplugin#28]
**Describe the bug**
 Timezone 'Asia/Ulaanbaatar' аас ялгаатай үед $invoice_due_date буруу үүсэхээр байна.

**Additional context**
class-qplugin-wc-payment-gateway.php файл дээр

```php
$dt = new DateTime();
$dt->setTimezone(new DateTimeZone('Asia/Ulaanbaatar'));
$dt->modify('+2 minutes');

$invoice_due_date = $dt->format('Y-m-d H:i:s');
```

болгож өөрчлөсөн нь зөв байх, одоо байгаа алдаатай код нь 

```php
$invoice_due_date = date('Y-m-d H:i:s', strtotime('+2 minutes'));
```
болно.

**Comment by biligunb** [comment]
@btulga nice.
Local дээрээ шалгаж үзсэн үү?
Өөр timezone тойгоор

**Comment by biligunb** [comment]
Closed due to insufficient information
